src/config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: [:show]
  root 'static_pages#home'
  
  get '/home', to: 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :users do
    get "users/:id", to: "users#show", as: :user
    patch "users/:id", to: "users#update"
    get "users/:id/edit", to: "users#edit", as: :edit_user
  end
  
  resources :frames do
    post "release"                          # frame_release_path	POST	/frames/:frame_id/release
    get "review", to: "frames#new_review"
    patch "review", to: "frames#create_review"
    # resources :review, only: [:new, :create]
    resources :tags do
      patch "drag_and_drop", on: :member    # drag_and_drop_frame_tags_path   PUT	/frames/:frame_id/tags/:id/drag_and_drop
    end
  end

  # devise_for :users, skip: ['confirmations']  # 除外
  # http://localhost:3000/letter_opener で開発環境で送信されたメールの確認
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end


# new_user_session_path	    GET	  /users/sign_in	      devise/sessions#new
# user_session_path	        POST	/users/sign_in	      devise/sessions#create
# destroy_user_session_path	DELETE/users/sign_out	      devise/sessions#destroy
# new_user_password_path	  GET	  /users/password/new	  devise/passwords#new
# edit_user_password_path	  GET	  /users/password/edit	devise/passwords#edit
# user_password_path	      PATCH	/users/password	      devise/passwords#update
#                           POST	/users/password	      devise/passwords#create

# cancel_user_registration_path	GET	/users/cancel   devise/registrations#cancel
# new_user_registration_path	  GET	/users/sign_up	devise/registrations#new
# edit_user_registration_path	  GET	/users/edit	    devise/registrations#edit
# user_registration_path	      PATCH	/users	      devise/registrations#update
#                               DELETE	/users	    devise/registrations#destroy
#                               POST	/users	      devise/registrations#create

# new_user_confirmation_path	GET	/users/confirmation/new	  devise/confirmations#new
# user_confirmation_path	    GET	/users/confirmation	      devise/confirmations#show
#                             POST	/users/confirmation	    devise/confirmations#create

src/app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :frame, foreign_key: "frame_id"

  validates :text, presence: true, length: { maximum: 50 }

  AREA_NUM_VALUES = [1, 2, 3, 4]
  validates :area_num, inclusion: { in: AREA_NUM_VALUES }
  

end

src/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @frame = Frame.find_by(id: params[:frame_id])
    @tags = Tag.joins(:frame).where(frames: { user_id: current_user.id })
  end


  def new
    @frame = Frame.find_by(id: params[:frame_id])
    @tag = Tag.new
    @area_num_params = params[:area_num]
  end


  def create
    @frame = Frame.find_by(id: params[:frame_id])
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @tag.save
        format.html { redirect_to frame_tags_path(@frame.id), notice: 'ToDoが追加されました' }
        format.js { @status = "success" }
      else
        format.html { redirect_to frame_tags_path(@frame.id), notice: 'ToDoは入力エラーにより追加されませんでした' }
        format.js { @status = "fail" }
      end
    end

  end

  
  def edit
    @tag = Tag.find_by(id: params[:id])
    @frame = Frame.find_by(id: params[:frame_id])
    @area_num_params = params[:area_num]
  end


  def update
    @frame = Frame.find_by(id: params[:frame_id])
    @tags = Tag.joins(:frame).where(frames: { user_id: current_user.id })
    @tag = Tag.find_by(id: params[:id])
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to frame_tags_path(@frame.id), notice: 'ToDoが編集されました' }
        format.js { @status = "success" }
      else
        format.html { redirect_to frame_tags_path(@frame.id), notice: 'ToDoは入力エラーにより編集されませんでした' }
        format.js { @status = "fail" }
      end
    end
  end


  def destroy
    @frame = Frame.find_by(id: params[:frame_id])
    @tag = Tag.find_by(id: params[:id])
    @tags = Tag.joins(:frame).where(frames: { user_id: current_user.id })
    respond_to do |format|
      if @tag.destroy
        format.html { redirect_to frame_tags_path(@frame.id), notice: 'ToDoは削除されました' }
        format.js { @status = "success" }
      else
        format.html { redirect_to frame_tags_path(@frame.id), notice: 'ToDoは削除されませんでした' }
        format.js { @status = "fail" }
      end
    end
  end

  def drag_and_drop
    @frame = Frame.find_by(id: params[:frame_id])
    @tag = Tag.find_by(id: params[:id])
    @before_area_num = @tag.area_num    # 更新後に area_numを比較できる(@before_area_num => @tag.area_num)

    @tag.update(area_num: params[:area_num])
    @tags = Tag.joins(:frame).where(frames: { user_id: current_user.id })
    render formats: :js
  end


  private
    def tag_params
      # params.require(:tag).permit(:text, :privated)
      params.require(:tag).permit(:text, :privated, :frame_id, :area_num)
    end

end

src/app/helpers/tags_helper.rb
module TagsHelper
end

src/app/views/tags/_tag.html.erb
    <div class="card flex justify-between">
      <span class="w-5/6 truncate"><%= tag.text %></span>
      <span class="w-1/6 text-right">
      <%= link_to edit_frame_tag_path(tag.id, frame_id: @frame.id, area_num: area_num), remote: true, class: "edit-btn" do %>
      <i class="far fa-edit"></i>
      <% end %>
      </span>
    </div>

src/app/views/tags/_tag_form.html.erb
<div class="modal js-modal">
  <div class="modal__bg js-modal-close"></div>
  <div class="modal__content">

    <div class="text-right">
      <button id="close_btn">
      <%#= link_to tags_edit_frame_path(@frame.id), class: "p-5 -mr-7" do %>
      <%# <span class="btn-close"></span> %>
      <i class="fas fa-times fa-lg"></i> 
      </button>
      <%# end %>
    </div>

    <%# remote: trueにすることで、tags#createをjs(Ajax/create.js.erb)で処理 %>
    <%# ネストしているときの書き方 https://pikawaka.com/rails/form_with#%E3%83%8D%E3%82%B9%E3%83%88%E3%82%92%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E6%99%82%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9 %>
    <%= form_with(model: [@frame, @tag], local: false) do |f| %>
    <div id="error_partial">
      <%= render "./shared/error_messages", elm: @tag %>
    </div>

    <div class="field my-5 mx-auto">
      <div class="flex justify-between">
        <%= f.label :text %><br />
        <p class="text-center mx-0 mb-2">あと<span id="tag_text_now_count">50</span>文字</p>
      </div>
      <%= f.text_area :text, class:"h-20 border p-0.5 w-full resize-none" %>
    </div>

    <div class="field my-5 mx-auto">
      <%= f.label :privated %><br />
      <%= f.check_box :privated, class:"border h-5 w-5", as: :boolean %>
    </div>

    <%# frame_id,area_numの受渡し %>
    <%= f.hidden_field :area_num, value: @area_num_params %>
    <%= f.hidden_field :frame_id, value: @frame.id %>

    <div class="actions my-6 mx-auto flex">
      <% if controller.action_name == "new" %>
      <%= f.submit "作成", class:"block mx-auto btn", id: "tag_create_btn", disabled: true %>
      <% elsif controller.action_name == "edit" %>
      <%= f.submit "更新", class:"btn", id: "tag_create_btn", disabled: true %>
      <%= link_to "削除", frame_tag_path, method: :delete, class:"red-btn", remote: true %>
      <% end %>
    </div>

    <% end %>
  </div>

</div>

<script>
  $("#close_btn").on('click',function(){
    $('#tag_modal').fadeOut(10);
  })
</script>

src/app/views/tags/_tags.html.erb
<% @tags.where(area_num: area_num).each do |tag| %>
  <%= content_tag "div", id: "tag_card_#{tag.id}", class: "area_num_#{area_num} tag_card card flex justify-between",
    data: {update_url: drag_and_drop_frame_tag_path(tag.id, frame_id: @frame.id)} do %>
    <span class="w-5/6 truncate" id=<%= "tag_text_#{tag.id}" %>><%= tag.text %></span>
    <span class="w-1/6 text-right">
      <%= link_to edit_frame_tag_path(tag.id, frame_id: params[:frame_id], area_num: area_num), remote: true, class: "edit-btn" do %>
      <i class="far fa-edit"></i>
      <% end %>
    </span>
  <% end %>
<% end %>


src/app/views/tags/_tags_in_frame.html.erb
<div id=<%="tags_area_num_#{area_num}"%> class="w-full">
  <%# tags/update.js.erbのレンダリングのため、テンプレート化 %>
  <%= render "tags/tags", area_num: area_num %>
</div>
<div class="truncate h-full w-auto p-1 m-1 flex justify-center items-center">
  <div class="h-full w-full p-2">
    <%= link_to new_frame_tag_path(area_num: area_num), remote: true, class: "border-dashed border-2 bg-white flex justify-center items-center w-full h-full" do %>
    <i class="fas fa-plus"></i>
    <% end%>
  </div>
</div>

src/app/views/tags/create.js.erb
<% if @status == 'success' %>
	<% if @tag.area_num == 1 %>
  	$("#tags_area_num_1").append("<%= j(render("tag", tag: @tag, area_num: 1)) %>");
	<% elsif @tag.area_num == 2 %>
  	$("#tags_area_num_2").append("<%= j(render("tag", tag: @tag, area_num: 2)) %>");
	<% elsif @tag.area_num == 3 %>
  	$("#tags_area_num_3").append("<%= j(render("tag", tag: @tag, area_num: 3)) %>");
	<% elsif @tag.area_num == 4 %>
  	$("#tags_area_num_4").append("<%= j(render("tag", tag: @tag, area_num: 4)) %>");
	<% else %>
	  alert('error!');
	<% end %>
<%  elsif @status == 'fail' %>
  alert('error!');
<% end %>

$("#tag_modal").fadeOut(10);

src/app/views/tags/destroy.js.erb
<% if @status == 'success' %>
	<% if @tag.area_num == 1 %>
    $('#tags_area_num_1').html("<%= j(render "tags", area_num: 1) %>")
	<% elsif @tag.area_num == 2 %>
    $('#tags_area_num_2').html("<%= j(render "tags", area_num: 2) %>")
	<% elsif @tag.area_num == 3 %>
    $('#tags_area_num_3').html("<%= j(render "tags", area_num: 3) %>")
	<% elsif @tag.area_num == 4 %>
    $('#tags_area_num_4').html("<%= j(render "tags", area_num: 4) %>")
	<% else %>
	  alert('error!');
	<% end %>
<% elsif @status == 'fail' %>
  alert('error!');
<% end %>

$("#tag_modal").fadeOut(10);

src/app/views/tags/drag_and_drop.js.erb

	<% if @tag.area_num == 1 %>
    $('#tags_area_num_1').html('<%= j(render "tags", area_num: 1) %>')
	<% elsif @tag.area_num == 2 %>
    $('#tags_area_num_2').html('<%= j(render "tags", area_num: 2) %>')
	<% elsif @tag.area_num == 3 %>
    $('#tags_area_num_3').html('<%= j(render "tags", area_num: 3) %>')
	<% elsif @tag.area_num == 4 %>
    $('#tags_area_num_4').html('<%= j(render "tags", area_num: 4) %>')
	<% else %>
	  alert('error!');
	<% end %>

  <% if @before_area_num == 1 %>
    $('#tags_area_num_1').html('<%= j(render "tags", area_num: 1) %>')
	<% elsif @before_area_num == 2 %>
    $('#tags_area_num_2').html('<%= j(render "tags", area_num: 2) %>')
	<% elsif @before_area_num == 3 %>
    $('#tags_area_num_3').html('<%= j(render "tags", area_num: 3) %>')
	<% elsif @before_area_num == 4 %>
    $('#tags_area_num_4').html('<%= j(render "tags", area_num: 4) %>')
	<% else %>
	  alert('error!');
	<% end %>

src/app/views/tags/edit.js.erb
  $('#tag_modal').html('<%= escape_javascript(render partial: "tag_form") %>');
  $("#tag_modal").fadeIn(10);

  function tag_text_count(){

    const MAXIMUM_COUNT = 50;
    let text = document.getElementById('tag_text');
    let text_now_count = document.getElementById('tag_text_now_count');

    function btn_disabled() {
      let btn = document.getElementById('tag_create_btn');
      if ( text.value.length == 0 || text.value.length > MAXIMUM_COUNT) {
        btn.disabled = true;
      } else {
        btn.disabled = false;
      }
    }

    function text_count() {
      text_now_count.innerHTML = MAXIMUM_COUNT - text.value.length;
    }


    if (text == null) { 
      console.log("tag.textの文字数カウントは動作していません")
    } else {
      text.addEventListener('input', () => {
        text_count();
        btn_disabled();
      })
    }
  }

  tag_text_count()

src/app/views/tags/index.html.erb
<%= provide(:title, "Taskの作成") %>
<div class="bg-white">

<div class="inner-wrapper">

  <h1 class="text-2xl text-center font-bold m-3"><%= yield(:title) %></h1>


  <div class="wrapper">
    <div class="flex">
      <h2 class="h2 mb-1">Mission</h2>
      <%= link_to edit_frame_path(params[:frame_id]), class:"edit-btn ml-5" do %>
      <i class="far fa-edit"></i>
      <% end %>
    </div>
    <p class="rounded border p-2"><%= @frame.statement %></p>
  </div>

  <%# Ajax化でモーダル式のTag_newフォーム表示 %>
  <%# tags#createでframe_id,area_numを使うので、frame,area_numをtags#newにも渡す。 %>
  <div class="wrapper">
    <h2 class="h2 mb-1">Task</h2>
    <div id="tags_area_wrapper" class="h-screen">
      <div class="flex h-3/6 justify-between">
        <div id="area_num_1" class="border-r border-b bg-green-50 w-1/2 flex flex-col">
        <%= render "tags_in_frame", area_num: 1 %>
        </div>
        <div id="area_num_2" class="border-l border-b bg-blue-50 w-1/2 flex flex-col">
        <%= render "tags_in_frame", area_num: 2 %>
        </div>
      </div>
      <div class="flex h-3/6 justify-around">
        <div id="area_num_3" class="border-r border-t bg-yellow-50 w-1/2 flex flex-col">
        <%= render "tags_in_frame", area_num: 3 %>
        </div>
        <div id="area_num_4" class="border-l border-t bg-red-50 w-1/2 flex flex-col">
        <%= render "tags_in_frame", area_num: 4 %>
        </div>
      </div>
    </div>

    <div class="actions my-6 mx-auto flex">
    <%= link_to "投稿の公開", frame_release_path(@frame.id), method: :post, class:"btn  block mx-auto"%>
    <%= link_to "投稿の削除", frame_path(@frame), method: :delete, class:"frames-destroy red-btn block mx-auto bg-red-400" , data: { confirm: "本当によろしいですか？"}%>

      <%#= f.submit "投稿詳細の作成へ", class:"block mx-auto" %>
    </div>
  </div>
</div>


  <%# Tag_newのモーダルがここに表示される %>
  <div id="tag_modal"></div>

  <%# drag_and_drop.jsにframe.idを渡す用 %>
  <%#= hidden_field_tag "frame_id", @frame.id %>
</div>


src/app/views/tags/new.js.erb
  $('#tag_modal').html('<%= escape_javascript(render partial: "tag_form") %>');
  $("#tag_modal").fadeIn(10);

  function tag_text_count(){

    const MAXIMUM_COUNT = 50;
    let text = document.getElementById('tag_text');
    let text_now_count = document.getElementById('tag_text_now_count');

    function btn_disabled() {
      let btn = document.getElementById('tag_create_btn');
      if ( text.value.length == 0 || text.value.length > MAXIMUM_COUNT) {
        btn.disabled = true;
      } else {
        btn.disabled = false;
      }
    }

    function text_count() {
      text_now_count.innerHTML = MAXIMUM_COUNT - text.value.length;
    }


    if (text == null) { 
      console.log("tag.textの文字数カウントは動作していません")
    } else {
      text.addEventListener('input', () => {
        text_count();
        btn_disabled();
      })
    }
  }

  tag_text_count()


src/app/views/tags/update.js.erb
<% if @status == 'success' %>
	<% if @tag.area_num == 1 %>
    $('#tags_area_num_1').html("<%= j(render "tags", area_num: 1) %>")
	<% elsif @tag.area_num == 2 %>
    $('#tags_area_num_2').html("<%= j(render "tags", area_num: 2) %>")
	<% elsif @tag.area_num == 3 %>
    $('#tags_area_num_3').html("<%= j(render "tags", area_num: 3) %>")
	<% elsif @tag.area_num == 4 %>
    $('#tags_area_num_4').html("<%= j(render "tags", area_num: 4) %>")
	<% else %>
	  alert('error!');
	<% end %>
<% elsif @status == 'fail' %>
  alert('error!');
<% end %>

$("#tag_modal").fadeOut(10);