src/config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: [:show]
  root 'static_pages#home'
  
  get '/home', to: 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :users do
    get "users/:id", to: "users#show", as: :user
    patch "users/:id", to: "users#update"
    get "users/:id/edit", to: "users#edit", as: :edit_user
  end
  
  resources :frames do
    post "release"                          # frame_release_path	POST	/frames/:frame_id/release
    get "review", to: "frames#new_review"
    patch "review", to: "frames#create_review"
    # resources :review, only: [:new, :create]
    resources :tags do
      patch "drag_and_drop", on: :member    # drag_and_drop_frame_tags_path   PUT	/frames/:frame_id/tags/:id/drag_and_drop
    end
  end

  # devise_for :users, skip: ['confirmations']  # 除外
  # http://localhost:3000/letter_opener で開発環境で送信されたメールの確認
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end


# new_user_session_path	    GET	  /users/sign_in	      devise/sessions#new
# user_session_path	        POST	/users/sign_in	      devise/sessions#create
# destroy_user_session_path	DELETE/users/sign_out	      devise/sessions#destroy
# new_user_password_path	  GET	  /users/password/new	  devise/passwords#new
# edit_user_password_path	  GET	  /users/password/edit	devise/passwords#edit
# user_password_path	      PATCH	/users/password	      devise/passwords#update
#                           POST	/users/password	      devise/passwords#create

# cancel_user_registration_path	GET	/users/cancel   devise/registrations#cancel
# new_user_registration_path	  GET	/users/sign_up	devise/registrations#new
# edit_user_registration_path	  GET	/users/edit	    devise/registrations#edit
# user_registration_path	      PATCH	/users	      devise/registrations#update
#                               DELETE	/users	    devise/registrations#destroy
#                               POST	/users	      devise/registrations#create

# new_user_confirmation_path	GET	/users/confirmation/new	  devise/confirmations#new
# user_confirmation_path	    GET	/users/confirmation	      devise/confirmations#show
#                             POST	/users/confirmation	    devise/confirmations#create

src/app/views/shared/_error_messages.html.erb
<% if elm.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% elm.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

src/app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
<p class="alert alert-<%= key %>">
  <%= value %>
</p>
<% end %>

src/app/views/shared/_frames.html.erb
<% frames.each do |frame| %>
<div class="wrapper">
  <div class="inner-wrapper">
    <div class="pb-2 flex justify-between">
      <div class="flex">
        <%= render "shared/user_image", { image: frame.user.image, size: 10 } %>    
        <div class="ml-2">
          <p class="font-bold"><%= frame.user.name %></p>
          <p class="text-gray-600"><%= l frame.created_at, format: :date_with_time %></p>
        </div>
      </div>
      <% if current_user && frame.user_id == current_user.id %>
        <div class="flex">
          <%= link_to frame_tags_path(frame_id: frame.id), class: "mr-1 edit-btn edit_frame_#{frame.id}" do %>
            <p>edit</p>
          <% end %>
          <%= link_to frame_review_path(frame_id: frame.id), class: "edit-btn edit_frame_#{frame.id}" do %>
            <p>review</p>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="pb-2">
      <p class="text-lg">Mission</p>
      <p><%= frame.statement %></p>
    </div>

    <div class="h-80 pb-2">
      <div class="flex h-3/6 justify-between">
      <%= render "shared/tags_in_frames", { area_num: 1, frame: frame, border_and_bg_color: "border-r border-b bg-green-50 " } %>
      <%= render "shared/tags_in_frames", { area_num: 2, frame: frame, border_and_bg_color: "border-l border-b bg-blue-50 " } %>
      </div>

      <div class="flex h-3/6 justify-around">
      <%= render "shared/tags_in_frames", { area_num: 3, frame: frame, border_and_bg_color: "border-r border-t bg-yellow-50 " } %>
      <%= render "shared/tags_in_frames", { area_num: 4, frame: frame, border_and_bg_color: "border-l border-t bg-red-50 " } %>

      </div>
    </div>

    <% if frame.review.present? %>
    <div class="">
      <div class="flex justify-between">
        <p class="text-lg">review</p>
        <p class="text-gray-600"><%= frame.reviewed_at %></p>
      </div>
      <p><%= frame.review %></p>
    </div>
    <% end %>
  </div>
</div>
<% end %>

src/app/views/shared/_tags_in_frames.html.erb
<div class="<%= border_and_bg_color %> w-1/2 flex flex-col h-full">
  <% Tag.where(frame_id: frame.id, area_num: area_num).each_with_index do |tag, i| %>
    <% if i == 3 %>
      <%= content_tag "div", class: "flex justify-center items-center h-full" do %>
        <i class="fas fa-ellipsis-v w-full text-center"></i>
      <% end %>
      <% break %>
    <% end %>
    <%= content_tag "div", class: "card flex justify-between" do %>
      <span class="w-5/6 truncate"><%= tag.text %></span>
    <% end %>
  <% end %>
</div>

src/app/views/shared/_user_image.html.erb
<div class="relative w-<%=size%> h-<%=size%> rounded-full overflow-hidden border-green-600 border-2">
  <% if image.present? %>
    <%= image_tag image.url, class:"absolute inset-0 ", width: "100%" %>
  <% else %>
    <%= image_pack_tag "default_user_image.png", class:"absolute inset-0", width: "100%" %>
  <% end %>
</div>