src/config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: [:show]
  root 'static_pages#home'
  
  get '/home', to: 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :users do
    get "users/:id", to: "users#show", as: :user
    patch "users/:id", to: "users#update"
    get "users/:id/edit", to: "users#edit", as: :edit_user
  end
  
  resources :frames do
    post "release"                          # frame_release_path	POST	/frames/:frame_id/release
    get "review", to: "frames#new_review"
    patch "review", to: "frames#create_review"
    # resources :review, only: [:new, :create]
    resources :tags do
      patch "drag_and_drop", on: :member    # drag_and_drop_frame_tags_path   PUT	/frames/:frame_id/tags/:id/drag_and_drop
    end
  end

  # devise_for :users, skip: ['confirmations']  # 除外
  # http://localhost:3000/letter_opener で開発環境で送信されたメールの確認
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end


# new_user_session_path	    GET	  /users/sign_in	      devise/sessions#new
# user_session_path	        POST	/users/sign_in	      devise/sessions#create
# destroy_user_session_path	DELETE/users/sign_out	      devise/sessions#destroy
# new_user_password_path	  GET	  /users/password/new	  devise/passwords#new
# edit_user_password_path	  GET	  /users/password/edit	devise/passwords#edit
# user_password_path	      PATCH	/users/password	      devise/passwords#update
#                           POST	/users/password	      devise/passwords#create

# cancel_user_registration_path	GET	/users/cancel   devise/registrations#cancel
# new_user_registration_path	  GET	/users/sign_up	devise/registrations#new
# edit_user_registration_path	  GET	/users/edit	    devise/registrations#edit
# user_registration_path	      PATCH	/users	      devise/registrations#update
#                               DELETE	/users	    devise/registrations#destroy
#                               POST	/users	      devise/registrations#create

# new_user_confirmation_path	GET	/users/confirmation/new	  devise/confirmations#new
# user_confirmation_path	    GET	/users/confirmation	      devise/confirmations#show
#                             POST	/users/confirmation	    devise/confirmations#create

src/app/views/layouts/_footer.html.erb
<footer class="bg-white">
  <nav class="fixed bottom-0 h-10 w-screen bg-white flex justify-between items-center">
  <% if user_signed_in? %>
    <%= link_to new_frame_path, class: "w-1/4 flex flex-col justify-between items-center" do%>
    <i class="h-3/4 fas fa-lg fa-pencil-alt"></i>
    <p class="h-1/4 text-xs">create</p>
    <% end %>
  <% end %>
    <%= link_to frames_path, class: "w-1/4 flex flex-col justify-between items-center" do %>
    <i class="h-3/4 fas fa-lg fa-home"></i>
    <p class="h-1/4 text-xs">home</p>
    <% end %>
    <%= link_to "#", class: "w-1/4 flex flex-col justify-between items-center" do %>
    <i class="h-3/4 fas fa-lg fa-chart-pie"></i>
    <p class="h-1/4 text-xs">月合計</p>
    <% end %>
    <%= link_to "#", class: "w-1/4 flex flex-col justify-between items-center" do %>
    <i class="h-3/4 fas fa-lg fa-chart-bar"></i>
    <p class="h-1/4 text-xs">年合計</p>
    <% end %>
  </nav>
</footer>

src/app/views/layouts/_header.html.erb
<header class="bg-white">
  <nav class="border-b h-10 flex justify-between items-center">
    <%= image_pack_tag "media/images/logo-small.png", class: "h-10" %>
    <div class="flex">
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete, class: "flex justify-center items-center" do %>
          <i class="fas  fa-lg fa-sign-out-alt m-2"></i>
        <% end %>
        <%= link_to user_path(current_user), class: "flex justify-center items-center" do %>
          <i class="fas fa-lg fa-users-cog m-2"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "flex justify-center items-center" do %>
          <i class="fas fa-lg fa-sign-in-alt m-2"></i>
        <% end %>
      <% end %>
    </div>
  </nav>
</header>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title><%= full_title(yield(:title)) %></title>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="mx-auto mb-20 bg-gray-100">
      <%= render 'shared/flash' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>